name: wasteagram
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^0.14.0
  firebase_storage: ^4.0.0
  firebase_core: ^0.5.0
  intl: ^0.16.0
  location: ^3.0.0
  image_picker: ^0.6.7
  test: ^1.16.5
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
